[package]
name = "squaring"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
criterion = "0.3"

[dev-dependency]

[[bench]]
name = "squaring_benchmark"
harness = false             # We instruct Rust to disable its own test framework.
